modified: post data is fetched from fbase
The following error occurs if we set 'post' object in state for internal routing.
error: Failed to execute 'pushState' on 'History': [object Object] could not be cloned.

possible fix, need to use localStorage